name: Java Build

on: [ push ]

jobs:
    build:
        name: Maven Build
        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v4

        -   name: Set up JDK 11
            uses: actions/setup-java@v4
            with:
                java-version: 11
                distribution: temurin
                cache: maven

        -   uses: carlosperate/arm-none-eabi-gcc-action@v1
        -   run: arm-none-eabi-gcc --version

        -   run: sudo apt-get update
        -   run: sudo apt-get install gcc-multilib g++-multilib
        -   run: gcc --version

        -   name: Build with Maven
            run: ./mvnw -B install --file pom.xml
